import { redirect } from "next/navigation";
import Link from "next/link";
import { getCurrentUser } from "@/src/lib/auth/session";

export default async function DashboardPage() {
  const user = await getCurrentUser();

    if (!user) {
        redirect("/login");
          }

            const displayName =
                user.firstName ||
                    user.username ||
                        user.email.split("@")[0];

                          return (
                              <main className="dashboard-page">
                                    <header className="dashboard-header">
                                            <Link href="/" className="dashboard-logo">
                                                      PROGRACE <span>360</span>
                                                              </Link>

                                                                      <div className="dashboard-user">
                                                                                <div className="dashboard-avatar">
                                                                                            {displayName.charAt(0).toUpperCase()}
                                                                                                      </div>

                                                                                                                <div>
                                                                                                                            <strong>{displayName}</strong>
                                                                                                                                        <small>{user.email}</small>
                                                                                                                                                  </div>
                                                                                                                                                          </div>
                                                                                                                                                                </header>

                                                                                                                                                                      <section className="dashboard-content">
                                                                                                                                                                              <div className="dashboard-intro">
                                                                                                                                                                                        <p>VOTRE ESPACE PROGRACE 360</p>

                                                                                                                                                                                                  <h1>Bonjour, {displayName}.</h1>

                                                                                                                                                                                                            <span>
                                                                                                                                                                                                                        Votre environnement numérique professionnel est prêt.
                                                                                                                                                                                                                                  </span>
                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                  <div className="dashboard-grid">
                                                                                                                                                                                                                                                            <Link
                                                                                                                                                                                                                                                                        href="/business-manager"
                                                                                                                                                                                                                                                                                    className="dashboard-module featured"
                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                          <span>💼</span>

                                                                                                                                                                                                                                                                                                                      <h2>Business Manager</h2>

                                                                                                                                                                                                                                                                                                                                  <p>
                                                                                                                                                                                                                                                                                                                                                Gérez vos produits, ventes, dépenses,
                                                                                                                                                                                                                                                                                                                                                              clients et fournisseurs.
                                                                                                                                                                                                                                                                                                                                                                          </p>

                                                                                                                                                                                                                                                                                                                                                                                      <b>Ouvrir →</b>
                                                                                                                                                                                                                                                                                                                                                                                                </Link>

                                                                                                                                                                                                                                                                                                                                                                                                          <article className="dashboard-module">
                                                                                                                                                                                                                                                                                                                                                                                                                      <span>🎓</span>

                                                                                                                                                                                                                                                                                                                                                                                                                                  <h2>PROGRACE Learning</h2>

                                                                                                                                                                                                                                                                                                                                                                                                                                              <p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                            Développez vos compétences et progressez.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <b>Bientôt disponible</b>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </article>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <article className="dashboard-module">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <span>📚</span>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <h2>Bibliothèque</h2>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Livres, guides et ressources professionnelles.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <b>Bientôt disponible</b>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </article>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <article className="dashboard-module">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <span>🛒</span>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <h2>Boutique</h2>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Produits numériques, formations et packs.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <b>Bientôt disponible</b>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </article>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <article className="dashboard-module">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <span>🤖</span>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <h2>Assistant PROGRACE</h2>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Votre assistant numérique pour avancer plus vite.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <b>Bientôt disponible</b>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </article>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <article className="dashboard-module">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <span>📊</span>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <h2>Insights</h2>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Conseils, actualités et informations utiles.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <b>Bientôt disponible</b>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </article>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }